services:
  - type: web
    name: codecraze-anti
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    branch: CRAZE
    runtime: python